import type { CharacterCreationOption } from "@dnd/types";

export const characterCreationContentSource = {
  source: "dnd-companion-mvp",
  sourceVersion: "2026-06-mvp",
} as const;

type CharacterCreationOptionSeed = Omit<
  CharacterCreationOption,
  "id" | "source" | "sourceVersion"
> & {
  displayOrder: number;
};

const option = (
  seed: CharacterCreationOptionSeed,
): CharacterCreationOption & { displayOrder: number } => ({
  ...seed,
  id: `character-option-${seed.slug}`,
  source: characterCreationContentSource.source,
  sourceVersion: characterCreationContentSource.sourceVersion,
});

export const coreCharacterCreationOptions = [
  option({
    abilities: [
      {
        name: "Second Wind",
        summary: "Pause, steady yourself, and recover a small reserve of stamina.",
        trigger: "Bonus action, once per rest",
      },
      {
        name: "Action Surge",
        summary: "Push beyond your usual pace to take one additional action.",
        trigger: "Once per rest",
      },
    ],
    actions: ["Hold a front line", "Protect an ally", "Adapt weapons to the moment"],
    category: "class",
    displayOrder: 10,
    flavour: "Your training shows in calm footwork, measured breath, and decisive action.",
    gameplay: "A direct, resilient adventurer with flexible combat choices.",
    magicCapable: false,
    name: "Fighter",
    proficiencies: ["Weapons", "Armour", "Physical pressure"],
    quirks: ["Keeps equipment close", "Reads a room by its exits"],
    slug: "fighter",
    summary: "A trained combatant who protects the party and adapts under pressure.",
    traits: ["Reliable", "Tactical", "Hard to move"],
  }),
  option({
    abilities: [
      {
        name: "Sneak Attack",
        summary: "Exploit a distracted or exposed foe for a telling strike.",
        trigger: "When positioning creates an opening",
      },
      {
        name: "Cunning Action",
        summary: "Move, hide, or disengage with unusual speed.",
        trigger: "Bonus action",
      },
    ],
    actions: ["Scout ahead", "Open a difficult route", "Strike from advantage"],
    category: "class",
    displayOrder: 20,
    flavour: "You notice the loose stone, the hidden latch, and the moment attention slips.",
    gameplay: "A mobile problem-solver who rewards positioning and careful observation.",
    magicCapable: false,
    name: "Rogue",
    proficiencies: ["Skills", "Finesse weapons", "Tools"],
    quirks: ["Always has a second route", "Touches nothing without looking first"],
    slug: "rogue",
    summary: "A quick, skilful adventurer who turns openings into advantages.",
    traits: ["Observant", "Mobile", "Resourceful"],
  }),
  option({
    abilities: [
      {
        name: "Spellcasting",
        summary: "Prepare divine magic that can protect, restore, reveal, or punish.",
        trigger: "Uses prepared spells and spell slots",
      },
      {
        name: "Channel Divinity",
        summary: "Call on a focused expression of sacred power.",
        trigger: "Limited use between rests",
      },
    ],
    actions: ["Restore an ally", "Ward the party", "Call on sacred authority"],
    category: "class",
    displayOrder: 30,
    flavour: "Your faith may be quiet, fierce, questioning, or carried like an old promise.",
    gameplay: "A durable divine spellcaster who supports allies and answers danger.",
    magicCapable: true,
    name: "Cleric",
    proficiencies: ["Divine magic", "Armour", "Insight"],
    quirks: ["Keeps a ritual close", "Notices broken vows"],
    slug: "cleric",
    summary: "A divine guide who combines resilient support with meaningful magic.",
    traits: ["Protective", "Purposeful", "Spiritually grounded"],
  }),
  option({
    abilities: [
      {
        name: "Spellcasting",
        summary: "Shape arcane spells from a studied spellbook.",
        trigger: "Uses prepared spells and spell slots",
      },
      {
        name: "Arcane Recovery",
        summary: "Use a quiet pause to recover part of your magical reserve.",
        trigger: "After a short rest",
      },
    ],
    actions: ["Control the battlefield", "Solve a problem with magic", "Recall hidden lore"],
    category: "class",
    displayOrder: 40,
    flavour: "Every spell is a solved mystery, and every mystery suggests another spell.",
    gameplay: "A versatile arcane spellcaster with many answers and limited endurance.",
    magicCapable: true,
    name: "Wizard",
    proficiencies: ["Arcane lore", "Rituals", "Prepared spells"],
    quirks: ["Annotates everything", "Collects questions as eagerly as treasure"],
    slug: "wizard",
    summary: "A studied spellcaster who prepares the right tool for an uncertain day.",
    traits: ["Curious", "Prepared", "Arcane"],
  }),
  option({
    abilities: [],
    actions: ["Adapt to unfamiliar people", "Learn a new local habit quickly"],
    category: "ancestry",
    displayOrder: 10,
    flavour: "Your story is shaped less by one inherited path and more by the people around you.",
    gameplay: "A flexible ancestry choice that fits almost any concept.",
    magicCapable: false,
    name: "Human",
    proficiencies: ["Adaptability", "Community"],
    quirks: ["Picks up local sayings", "Finds common ground quickly"],
    slug: "human",
    summary: "Adaptable, ambitious, and shaped by a wide range of cultures.",
    traits: ["Versatile", "Driven", "Connected"],
  }),
  option({
    abilities: [],
    actions: ["Notice subtle movement", "Remain composed during long watches"],
    category: "ancestry",
    displayOrder: 20,
    flavour: "Long memory can feel like wisdom, responsibility, or a weight no one else sees.",
    gameplay: "A perceptive ancestry with graceful movement and an old cultural memory.",
    magicCapable: false,
    name: "Elf",
    proficiencies: ["Perception", "Grace", "Long memory"],
    quirks: ["Pauses before answering", "Treats old places as living witnesses"],
    slug: "elf",
    summary: "Keen-sensed and graceful, carrying memories that outlast many kingdoms.",
    traits: ["Perceptive", "Patient", "Otherworldly"],
  }),
  option({
    abilities: [],
    actions: ["Stand firm", "Judge stonework and crafted things"],
    category: "ancestry",
    displayOrder: 30,
    flavour: "Promises are built to last, whether they concern a bridge, a blade, or a friendship.",
    gameplay: "A sturdy ancestry with strong traditions and practical craft knowledge.",
    magicCapable: false,
    name: "Dwarf",
    proficiencies: ["Resilience", "Craft", "Stone lore"],
    quirks: ["Tests the workmanship", "Remembers every promise"],
    slug: "dwarf",
    summary: "Steadfast and practical, with deep respect for craft, kin, and promises.",
    traits: ["Resilient", "Grounded", "Loyal"],
  }),
  option({
    abilities: [],
    actions: ["Slip through a crowd", "Keep courage when danger feels too large"],
    category: "ancestry",
    displayOrder: 40,
    flavour: "Comfort matters, but so does discovering what lies beyond the next hill.",
    gameplay: "A nimble ancestry whose courage often arrives before anyone expects it.",
    magicCapable: false,
    name: "Halfling",
    proficiencies: ["Stealth", "Hospitality", "Unexpected courage"],
    quirks: ["Carries a familiar snack", "Makes strangers feel briefly at home"],
    slug: "halfling",
    summary: "Small, warm-hearted, and remarkably difficult to frighten away.",
    traits: ["Nimble", "Brave", "Sociable"],
  }),
  option({
    abilities: [],
    actions: ["Offer spiritual counsel", "Recognise ritual and religious custom"],
    category: "background",
    displayOrder: 10,
    flavour: "You have seen belief comfort people, control them, and sometimes do both at once.",
    gameplay: "Useful when faith, institutions, history, and moral pressure matter.",
    magicCapable: false,
    name: "Acolyte",
    proficiencies: ["Insight", "Religion", "Ritual etiquette"],
    quirks: ["Quotes a teaching at inconvenient moments", "Notices neglected shrines"],
    slug: "acolyte",
    summary: "Raised around sacred duties, difficult questions, and organised faith.",
    traits: ["Devout or questioning", "Empathetic", "Institution-aware"],
  }),
  option({
    abilities: [],
    actions: ["Read a dishonest deal", "Find contacts outside official channels"],
    category: "background",
    displayOrder: 20,
    flavour: "You know which rules are enforced, which are theatre, and who profits from both.",
    gameplay: "Useful for underworld contacts, deception, infiltration, and street knowledge.",
    magicCapable: false,
    name: "Criminal",
    proficiencies: ["Deception", "Stealth", "Underworld contacts"],
    quirks: ["Checks for tails", "Distrusts a deal without an escape route"],
    slug: "criminal",
    summary: "Experienced with hidden networks, risky bargains, and unofficial routes.",
    traits: ["Cautious", "Connected", "Pragmatic"],
  }),
  option({
    abilities: [],
    actions: ["Research an obscure lead", "Recognise a forgotten reference"],
    category: "background",
    displayOrder: 30,
    flavour: "The answer is probably in a book, a ruin, or the one source everyone ignored.",
    gameplay: "Useful for investigation, history, languages, and patient research.",
    magicCapable: false,
    name: "Sage",
    proficiencies: ["History", "Investigation", "Research"],
    quirks: ["Corrects dates under stress", "Keeps notes no one else can parse"],
    slug: "sage",
    summary: "A researcher driven by knowledge, unanswered questions, and old evidence.",
    traits: ["Analytical", "Curious", "Methodical"],
  }),
  option({
    abilities: [],
    actions: ["Keep order under pressure", "Recognise military tactics and ranks"],
    category: "background",
    displayOrder: 40,
    flavour: "Discipline kept you alive, but it did not answer what the fighting was for.",
    gameplay: "Useful for command, endurance, battlefield awareness, and military contacts.",
    magicCapable: false,
    name: "Soldier",
    proficiencies: ["Athletics", "Intimidation", "Military practice"],
    quirks: ["Counts supplies automatically", "Sleeps facing the door"],
    slug: "soldier",
    summary: "Shaped by discipline, conflict, and the people who stood beside you.",
    traits: ["Disciplined", "Alert", "Team-minded"],
  }),
  option({
    abilities: [],
    actions: ["Step between danger and an ally", "Take responsibility when plans fail"],
    category: "roleplay-trait",
    displayOrder: 10,
    flavour: "You are at your clearest when someone else needs you to stand firm.",
    gameplay: "A strong prompt for protective choices, loyalty, and difficult sacrifices.",
    magicCapable: false,
    name: "Steadfast guardian",
    proficiencies: [],
    quirks: ["Offers help before advice", "Takes the outside seat"],
    slug: "steadfast-guardian",
    summary: "A steadfast guardian who steps between danger and the people they trust.",
    traits: ["Protective", "Loyal", "Responsible"],
  }),
  option({
    abilities: [],
    actions: ["Follow an unanswered clue", "Risk comfort for understanding"],
    category: "roleplay-trait",
    displayOrder: 20,
    flavour: "A closed door is not a warning. It is an unfinished sentence.",
    gameplay: "A prompt for investigation, temptation, and consequences born from curiosity.",
    magicCapable: false,
    name: "Forbidden seeker",
    proficiencies: [],
    quirks: ["Asks one question too many", "Keeps dangerous fragments"],
    slug: "forbidden-seeker",
    summary: "A forbidden seeker drawn toward mysteries that wiser people leave alone.",
    traits: ["Curious", "Restless", "Tempted by secrets"],
  }),
  option({
    abilities: [],
    actions: ["Volunteer for the hard task", "Turn doubt into visible effort"],
    category: "roleplay-trait",
    displayOrder: 30,
    flavour: "Every success is evidence that you deserve the place you have fought to reach.",
    gameplay: "A prompt for ambition, insecurity, rivalry, and meaningful recognition.",
    magicCapable: false,
    name: "Unproven champion",
    proficiencies: [],
    quirks: ["Hides uncertainty behind preparation", "Remembers every slight"],
    slug: "unproven-champion",
    summary: "An unproven champion determined to earn a place no one can question.",
    traits: ["Ambitious", "Prepared", "Sensitive to doubt"],
  }),
  option({
    abilities: [],
    actions: ["Break tension with warmth", "Help the group recover after a setback"],
    category: "roleplay-trait",
    displayOrder: 40,
    flavour: "Hope is not denial. It is something you practise until others can carry it too.",
    gameplay: "A prompt for humour, morale, hidden sadness, and emotional leadership.",
    magicCapable: false,
    name: "Bright-hearted wanderer",
    proficiencies: [],
    quirks: ["Names camp meals", "Deflects concern with a story"],
    slug: "bright-hearted-wanderer",
    summary: "A bright-hearted wanderer who keeps the group moving when courage runs thin.",
    traits: ["Warm", "Resilient", "Emotionally perceptive"],
  }),
  ...([
    ["barbarian","Barbarian",false,"Rage","A fierce warrior who turns battle focus into strength and staying power."],
    ["bard","Bard",true,"Bardic Inspiration","A performer, diplomat, and spellcaster who helps allies shine."],
    ["druid","Druid",true,"Druidic","A keeper of primal magic who adapts through spells and animal forms."],
    ["monk","Monk",false,"Martial Arts","A disciplined combatant who relies on speed, focus, and precise technique."],
    ["paladin","Paladin",true,"Lay on Hands","An oath-bound champion who protects allies with steel and sacred power."],
    ["ranger","Ranger",true,"Favored Enemy","A watchful hunter and guide who excels beyond the safety of roads."],
    ["sorcerer","Sorcerer",true,"Sorcerous Origin","An innate spellcaster who bends a focused magical gift in unusual ways."],
    ["warlock","Warlock",true,"Pact Magic","A pact-bound spellcaster shaped by potent magic and lasting invocations."],
  ] as const).map(([slug,name,magicCapable,feature,summary],index) => option({ abilities: [{ name: feature, summary: `A defining ${name} feature ready for character reminders and the action hotbar.`, trigger: "Class feature" }, ...(magicCapable ? [{ name: "Spellcasting", summary: "Use class magic through the character spellbook.", trigger: "Uses spells and spell slots" }] : [])], actions: [feature, "Support the party with class expertise"], category: "class", displayOrder: 50 + index * 10, flavour: summary, gameplay: summary, magicCapable, name, proficiencies: ["Class weapons and tools", "Class saving throws"], quirks: ["Approaches danger through class training"], slug, summary, traits: ["Adventurous", "Capable", "Distinctive"] })),
  ...([
    ["gnome","Gnome","Clever and curious, with a knack for invention and subtle magic."],
    ["half-elf","Half-Elf","Adaptable and perceptive, carrying both human and elven heritage."],
    ["half-orc","Half-Orc","Powerful and enduring, with a reputation that often arrives first."],
    ["dragonborn","Dragonborn","Dragon-blooded and imposing, with elemental power close at hand."],
    ["tiefling","Tiefling","Marked by infernal heritage, with innate magic and a memorable presence."],
  ] as const).map(([slug,name,summary],index) => option({ abilities: [], actions: ["Draw on ancestral talents", "Bring a distinct perspective to the party"], category: "ancestry", displayOrder: 50 + index * 10, flavour: summary, gameplay: summary, magicCapable: false, name, proficiencies: ["Ancestral resilience", "Cultural knowledge"], quirks: ["Carries a tradition from home"], slug, summary, traits: ["Distinctive", "Resourceful", "Connected"] })),
] satisfies Array<CharacterCreationOption & { displayOrder: number }>;
