import type { RuleSnippet } from "@dnd/types";

export const coreRuleContentSource = {
  source: "dnd-5e-srd-mvp",
  sourceVersion: "2026-05-mvp",
} as const;

export type RuleSnippetSeed = RuleSnippet & {
  campaignId: null;
  contentKey: string;
  source: string;
  sourceVersion: string;
  tags: string[];
};

export const coreRuleSnippetSeeds: RuleSnippetSeed[] = [
  {
    aliases: ["blind", "blinded"],
    body:
      "A blinded creature cannot see. Its attack rolls are hindered, and attacks against it are easier while the attacker can exploit that lack of sight.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.blinded",
    id: "core-rule-blinded",
    slug: "blinded",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when sight is blocked or a creature cannot see its target.",
    tags: ["condition", "combat", "senses"],
    title: "Blinded",
    visibility: "player-safe",
  },
  {
    aliases: ["charm", "charmed"],
    body:
      "A charmed creature cannot target the charmer with hostile action and the charmer gains social leverage while interacting with it.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.charmed",
    id: "core-rule-charmed",
    slug: "charmed",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when influence limits hostile action against the charmer.",
    tags: ["condition", "social", "control"],
    title: "Charmed",
    visibility: "player-safe",
  },
  {
    aliases: ["deaf", "deafened"],
    body:
      "A deafened creature cannot hear and automatically fails checks that depend entirely on hearing.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.deafened",
    id: "core-rule-deafened",
    slug: "deafened",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when hearing-based awareness or effects matter.",
    tags: ["condition", "senses"],
    title: "Deafened",
    visibility: "player-safe",
  },
  {
    aliases: ["fear", "frightened"],
    body:
      "A frightened creature has trouble acting while the source of fear is visible and cannot willingly move closer to that source.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.frightened",
    id: "core-rule-frightened",
    slug: "frightened",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when fear affects movement and pressure against a visible source.",
    tags: ["condition", "movement", "control"],
    title: "Frightened",
    visibility: "player-safe",
  },
  {
    aliases: ["grapple", "grappled", "grappling"],
    body:
      "A grappled creature has no effective speed while the grapple lasts. The condition ends if the grappler is incapacitated or the creature is moved out of reach.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.grappled",
    id: "core-rule-grappled",
    slug: "grappled",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when a creature is held in place by a grappler or effect.",
    tags: ["condition", "movement", "combat"],
    title: "Grappled",
    visibility: "player-safe",
  },
  {
    aliases: ["incapacitated"],
    body:
      "An incapacitated creature cannot take actions or reactions, which often shuts off other active options.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.incapacitated",
    id: "core-rule-incapacitated",
    slug: "incapacitated",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when a creature cannot take actions or reactions.",
    tags: ["condition", "actions", "combat"],
    title: "Incapacitated",
    visibility: "player-safe",
  },
  {
    aliases: ["invisible", "invisibility"],
    body:
      "An invisible creature cannot be seen without special senses or magic. Attacks involving it usually shift advantage based on who can perceive whom.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.invisible",
    id: "core-rule-invisible",
    slug: "invisible",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when unseen positioning affects attacks and targeting.",
    tags: ["condition", "senses", "combat"],
    title: "Invisible",
    visibility: "player-safe",
  },
  {
    aliases: ["paralysis", "paralyzed"],
    body:
      "A paralyzed creature is incapacitated, cannot move or speak, and is especially vulnerable to nearby attacks.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.paralyzed",
    id: "core-rule-paralyzed",
    slug: "paralyzed",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when a creature is locked down and especially vulnerable.",
    tags: ["condition", "movement", "combat"],
    title: "Paralyzed",
    visibility: "player-safe",
  },
  {
    aliases: ["petrified", "petrification"],
    body:
      "A petrified creature is incapacitated, cannot move or speak, and becomes highly resistant to many forms of harm while transformed.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.petrified",
    id: "core-rule-petrified",
    slug: "petrified",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when a creature is transformed into inert solid material.",
    tags: ["condition", "transformation", "combat"],
    title: "Petrified",
    visibility: "player-safe",
  },
  {
    aliases: ["poison", "poisoned"],
    body:
      "A poisoned creature struggles with attacks and ability checks until the condition ends.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.poisoned",
    id: "core-rule-poisoned",
    slug: "poisoned",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when toxin, venom, or sickness interferes with action.",
    tags: ["condition", "checks", "combat"],
    title: "Poisoned",
    visibility: "player-safe",
  },
  {
    aliases: ["prone", "knocked down"],
    body:
      "A prone creature spends extra movement to stand and has trouble attacking. Nearby attackers can press the advantage, while distant attackers have a harder shot.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.prone",
    id: "core-rule-prone",
    slug: "prone",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when a creature is knocked down or chooses to drop low.",
    tags: ["condition", "movement", "combat"],
    title: "Prone",
    visibility: "player-safe",
  },
  {
    aliases: ["restrained", "restrain"],
    body:
      "A restrained creature has no effective speed, has trouble attacking and avoiding effects, and is easier for attackers to hit.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.restrained",
    id: "core-rule-restrained",
    slug: "restrained",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when bindings, webs, or force limit movement.",
    tags: ["condition", "movement", "combat"],
    title: "Restrained",
    visibility: "player-safe",
  },
  {
    aliases: ["stun", "stunned"],
    body:
      "A stunned creature is incapacitated, cannot move, can barely speak, and is easier to hit while the condition lasts.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.stunned",
    id: "core-rule-stunned",
    slug: "stunned",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary:
      "Use when a creature loses its turn pressure but remains standing.",
    tags: ["condition", "actions", "combat"],
    title: "Stunned",
    visibility: "player-safe",
  },
  {
    aliases: ["unconscious", "knocked out"],
    body:
      "An unconscious creature is incapacitated, unaware, drops what it holds, falls prone, and is especially vulnerable to nearby attacks.",
    campaignId: null,
    category: "condition",
    contentKey: "condition.unconscious",
    id: "core-rule-unconscious",
    slug: "unconscious",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when a creature drops, cannot act, and is highly vulnerable.",
    tags: ["condition", "combat", "survival"],
    title: "Unconscious",
    visibility: "player-safe",
  },
  {
    aliases: ["advantage", "disadvantage"],
    body:
      "Advantage means roll two d20s and use the higher result. Disadvantage means roll two d20s and use the lower result. If both apply, they cancel.",
    campaignId: null,
    category: "core-mechanic",
    contentKey: "core-mechanic.advantage-disadvantage",
    id: "core-rule-advantage-disadvantage",
    slug: "advantage-disadvantage",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Roll two d20s and keep the better or worse result.",
    tags: ["core-mechanic", "d20", "checks"],
    title: "Advantage and disadvantage",
    visibility: "player-safe",
  },
  {
    aliases: ["concentration", "concentrating"],
    body:
      "A creature can concentrate on one qualifying spell at a time. Damage, incapacitation, or certain environmental pressure can force a check or end concentration.",
    campaignId: null,
    category: "core-mechanic",
    contentKey: "core-mechanic.concentration",
    id: "core-rule-concentration",
    slug: "concentration",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary:
      "Track spell focus, damage checks, and conflicts with other concentration spells.",
    tags: ["core-mechanic", "spellcasting", "checks"],
    title: "Concentration",
    visibility: "player-safe",
  },
  {
    aliases: [
      "death save",
      "death saves",
      "death saving throw",
      "death saving throws",
    ],
    body:
      "At 0 hit points, a creature may need death saving throws. Three successes stabilize, three failures can kill, and a natural 20 or damage can shift the situation quickly.",
    campaignId: null,
    category: "core-mechanic",
    contentKey: "core-mechanic.death-saving-throws",
    id: "core-rule-death-saving-throws",
    slug: "death-saving-throws",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when a player character starts a turn at 0 hit points.",
    tags: ["core-mechanic", "survival", "combat"],
    title: "Death saving throws",
    visibility: "player-safe",
  },
  {
    aliases: ["dash action", "dash"],
    body:
      "Use your action to gain extra movement for the turn, usually equal to your current speed after modifiers.",
    campaignId: null,
    category: "core-mechanic",
    contentKey: "core-mechanic.action.dash",
    id: "core-rule-action-dash",
    slug: "action-dash",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Trade your action for extra movement this turn.",
    tags: ["core-mechanic", "common-action", "action-hotbar", "action"],
    title: "Dash",
    visibility: "player-safe",
  },
  {
    aliases: ["disengage action", "disengage"],
    body:
      "Use your action to move more carefully so your movement this turn does not normally invite opportunity attacks.",
    campaignId: null,
    category: "core-mechanic",
    contentKey: "core-mechanic.action.disengage",
    id: "core-rule-action-disengage",
    slug: "action-disengage",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Move away without normally inviting opportunity attacks.",
    tags: ["core-mechanic", "common-action", "action-hotbar", "action"],
    title: "Disengage",
    visibility: "player-safe",
  },
  {
    aliases: ["dodge action", "dodge"],
    body:
      "Use your action to focus on defence. Visible attackers have a harder time hitting you, and you are better positioned against avoidable effects until your next turn while you can still act.",
    campaignId: null,
    category: "core-mechanic",
    contentKey: "core-mechanic.action.dodge",
    id: "core-rule-action-dodge",
    slug: "action-dodge",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Focus on defence until the start of your next turn.",
    tags: ["core-mechanic", "common-action", "action-hotbar", "action"],
    title: "Dodge",
    visibility: "player-safe",
  },
  {
    aliases: ["help action", "help"],
    body:
      "Use your action to assist an ally with a task or create a useful opening against a nearby foe when the situation allows it.",
    campaignId: null,
    category: "core-mechanic",
    contentKey: "core-mechanic.action.help",
    id: "core-rule-action-help",
    slug: "action-help",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Assist an ally with a task or nearby attack.",
    tags: ["core-mechanic", "common-action", "action-hotbar", "action"],
    title: "Help",
    visibility: "player-safe",
  },
  {
    aliases: ["hide action", "hide"],
    body:
      "Use your action to try to become unseen when your position, cover, and surroundings make hiding possible.",
    campaignId: null,
    category: "core-mechanic",
    contentKey: "core-mechanic.action.hide",
    id: "core-rule-action-hide",
    slug: "action-hide",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Try to become unseen when the surroundings allow it.",
    tags: ["core-mechanic", "common-action", "action-hotbar", "action"],
    title: "Hide",
    visibility: "player-safe",
  },
  {
    aliases: ["opportunity attack", "opportunity attacks"],
    body:
      "A creature can often use its reaction to make a melee attack when a hostile creature leaves its reach. Forced movement and some movement options may avoid it.",
    campaignId: null,
    category: "core-mechanic",
    contentKey: "core-mechanic.opportunity-attacks",
    id: "core-rule-opportunity-attacks",
    slug: "opportunity-attacks",
    source: coreRuleContentSource.source,
    sourceVersion: coreRuleContentSource.sourceVersion,
    summary: "Use when a creature leaves an enemy reach during movement.",
    tags: ["core-mechanic", "movement", "reactions"],
    title: "Opportunity attacks",
    visibility: "player-safe",
  },
];

export const coreRuleSnippets: RuleSnippet[] = coreRuleSnippetSeeds.map(
  (rule) => ({ ...rule }),
);
