create table if not exists character_creation_options (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  category text not null check (
    category in ('class', 'ancestry', 'background', 'roleplay-trait')
  ),
  name text not null,
  summary text not null,
  gameplay text not null default '',
  flavour text not null default '',
  actions jsonb not null default '[]'::jsonb,
  traits jsonb not null default '[]'::jsonb,
  proficiencies jsonb not null default '[]'::jsonb,
  quirks jsonb not null default '[]'::jsonb,
  ability_summaries jsonb not null default '[]'::jsonb,
  magic_capable boolean not null default false,
  source text not null default 'dnd-companion-mvp',
  source_version text not null default '2026-06-mvp',
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists character_creation_options_category_order_idx
  on character_creation_options (category, display_order, name);

insert into character_creation_options (
  slug,
  category,
  name,
  summary,
  gameplay,
  flavour,
  actions,
  traits,
  proficiencies,
  quirks,
  ability_summaries,
  magic_capable,
  source,
  source_version,
  display_order
) values
  (
    'fighter',
    'class',
    'Fighter',
    'A trained combatant who protects the party and adapts under pressure.',
    'A direct, resilient adventurer with flexible combat choices.',
    'Your training shows in calm footwork, measured breath, and decisive action.',
    '["Hold a front line","Protect an ally","Adapt weapons to the moment"]'::jsonb,
    '["Reliable","Tactical","Hard to move"]'::jsonb,
    '["Weapons","Armour","Physical pressure"]'::jsonb,
    '["Keeps equipment close","Reads a room by its exits"]'::jsonb,
    '[{"name":"Second Wind","summary":"Pause, steady yourself, and recover a small reserve of stamina.","trigger":"Bonus action, once per rest"},{"name":"Action Surge","summary":"Push beyond your usual pace to take one additional action.","trigger":"Once per rest"}]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    10
  ),
  (
    'rogue',
    'class',
    'Rogue',
    'A quick, skilful adventurer who turns openings into advantages.',
    'A mobile problem-solver who rewards positioning and careful observation.',
    'You notice the loose stone, the hidden latch, and the moment attention slips.',
    '["Scout ahead","Open a difficult route","Strike from advantage"]'::jsonb,
    '["Observant","Mobile","Resourceful"]'::jsonb,
    '["Skills","Finesse weapons","Tools"]'::jsonb,
    '["Always has a second route","Touches nothing without looking first"]'::jsonb,
    '[{"name":"Sneak Attack","summary":"Exploit a distracted or exposed foe for a telling strike.","trigger":"When positioning creates an opening"},{"name":"Cunning Action","summary":"Move, hide, or disengage with unusual speed.","trigger":"Bonus action"}]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    20
  ),
  (
    'cleric',
    'class',
    'Cleric',
    'A divine guide who combines resilient support with meaningful magic.',
    'A durable divine spellcaster who supports allies and answers danger.',
    'Your faith may be quiet, fierce, questioning, or carried like an old promise.',
    '["Restore an ally","Ward the party","Call on sacred authority"]'::jsonb,
    '["Protective","Purposeful","Spiritually grounded"]'::jsonb,
    '["Divine magic","Armour","Insight"]'::jsonb,
    '["Keeps a ritual close","Notices broken vows"]'::jsonb,
    '[{"name":"Spellcasting","summary":"Prepare divine magic that can protect, restore, reveal, or punish.","trigger":"Uses prepared spells and spell slots"},{"name":"Channel Divinity","summary":"Call on a focused expression of sacred power.","trigger":"Limited use between rests"}]'::jsonb,
    true,
    'dnd-companion-mvp',
    '2026-06-mvp',
    30
  ),
  (
    'wizard',
    'class',
    'Wizard',
    'A studied spellcaster who prepares the right tool for an uncertain day.',
    'A versatile arcane spellcaster with many answers and limited endurance.',
    'Every spell is a solved mystery, and every mystery suggests another spell.',
    '["Control the battlefield","Solve a problem with magic","Recall hidden lore"]'::jsonb,
    '["Curious","Prepared","Arcane"]'::jsonb,
    '["Arcane lore","Rituals","Prepared spells"]'::jsonb,
    '["Annotates everything","Collects questions as eagerly as treasure"]'::jsonb,
    '[{"name":"Spellcasting","summary":"Shape arcane spells from a studied spellbook.","trigger":"Uses prepared spells and spell slots"},{"name":"Arcane Recovery","summary":"Use a quiet pause to recover part of your magical reserve.","trigger":"After a short rest"}]'::jsonb,
    true,
    'dnd-companion-mvp',
    '2026-06-mvp',
    40
  ),
  (
    'human',
    'ancestry',
    'Human',
    'Adaptable, ambitious, and shaped by a wide range of cultures.',
    'A flexible ancestry choice that fits almost any concept.',
    'Your story is shaped less by one inherited path and more by the people around you.',
    '["Adapt to unfamiliar people","Learn a new local habit quickly"]'::jsonb,
    '["Versatile","Driven","Connected"]'::jsonb,
    '["Adaptability","Community"]'::jsonb,
    '["Picks up local sayings","Finds common ground quickly"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    10
  ),
  (
    'elf',
    'ancestry',
    'Elf',
    'Keen-sensed and graceful, carrying memories that outlast many kingdoms.',
    'A perceptive ancestry with graceful movement and an old cultural memory.',
    'Long memory can feel like wisdom, responsibility, or a weight no one else sees.',
    '["Notice subtle movement","Remain composed during long watches"]'::jsonb,
    '["Perceptive","Patient","Otherworldly"]'::jsonb,
    '["Perception","Grace","Long memory"]'::jsonb,
    '["Pauses before answering","Treats old places as living witnesses"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    20
  ),
  (
    'dwarf',
    'ancestry',
    'Dwarf',
    'Steadfast and practical, with deep respect for craft, kin, and promises.',
    'A sturdy ancestry with strong traditions and practical craft knowledge.',
    'Promises are built to last, whether they concern a bridge, a blade, or a friendship.',
    '["Stand firm","Judge stonework and crafted things"]'::jsonb,
    '["Resilient","Grounded","Loyal"]'::jsonb,
    '["Resilience","Craft","Stone lore"]'::jsonb,
    '["Tests the workmanship","Remembers every promise"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    30
  ),
  (
    'halfling',
    'ancestry',
    'Halfling',
    'Small, warm-hearted, and remarkably difficult to frighten away.',
    'A nimble ancestry whose courage often arrives before anyone expects it.',
    'Comfort matters, but so does discovering what lies beyond the next hill.',
    '["Slip through a crowd","Keep courage when danger feels too large"]'::jsonb,
    '["Nimble","Brave","Sociable"]'::jsonb,
    '["Stealth","Hospitality","Unexpected courage"]'::jsonb,
    '["Carries a familiar snack","Makes strangers feel briefly at home"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    40
  ),
  (
    'acolyte',
    'background',
    'Acolyte',
    'Raised around sacred duties, difficult questions, and organised faith.',
    'Useful when faith, institutions, history, and moral pressure matter.',
    'You have seen belief comfort people, control them, and sometimes do both at once.',
    '["Offer spiritual counsel","Recognise ritual and religious custom"]'::jsonb,
    '["Devout or questioning","Empathetic","Institution-aware"]'::jsonb,
    '["Insight","Religion","Ritual etiquette"]'::jsonb,
    '["Quotes a teaching at inconvenient moments","Notices neglected shrines"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    10
  ),
  (
    'criminal',
    'background',
    'Criminal',
    'Experienced with hidden networks, risky bargains, and unofficial routes.',
    'Useful for underworld contacts, deception, infiltration, and street knowledge.',
    'You know which rules are enforced, which are theatre, and who profits from both.',
    '["Read a dishonest deal","Find contacts outside official channels"]'::jsonb,
    '["Cautious","Connected","Pragmatic"]'::jsonb,
    '["Deception","Stealth","Underworld contacts"]'::jsonb,
    '["Checks for tails","Distrusts a deal without an escape route"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    20
  ),
  (
    'sage',
    'background',
    'Sage',
    'A researcher driven by knowledge, unanswered questions, and old evidence.',
    'Useful for investigation, history, languages, and patient research.',
    'The answer is probably in a book, a ruin, or the one source everyone ignored.',
    '["Research an obscure lead","Recognise a forgotten reference"]'::jsonb,
    '["Analytical","Curious","Methodical"]'::jsonb,
    '["History","Investigation","Research"]'::jsonb,
    '["Corrects dates under stress","Keeps notes no one else can parse"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    30
  ),
  (
    'soldier',
    'background',
    'Soldier',
    'Shaped by discipline, conflict, and the people who stood beside you.',
    'Useful for command, endurance, battlefield awareness, and military contacts.',
    'Discipline kept you alive, but it did not answer what the fighting was for.',
    '["Keep order under pressure","Recognise military tactics and ranks"]'::jsonb,
    '["Disciplined","Alert","Team-minded"]'::jsonb,
    '["Athletics","Intimidation","Military practice"]'::jsonb,
    '["Counts supplies automatically","Sleeps facing the door"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    40
  ),
  (
    'steadfast-guardian',
    'roleplay-trait',
    'Steadfast guardian',
    'A steadfast guardian who steps between danger and the people they trust.',
    'A strong prompt for protective choices, loyalty, and difficult sacrifices.',
    'You are at your clearest when someone else needs you to stand firm.',
    '["Step between danger and an ally","Take responsibility when plans fail"]'::jsonb,
    '["Protective","Loyal","Responsible"]'::jsonb,
    '[]'::jsonb,
    '["Offers help before advice","Takes the outside seat"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    10
  ),
  (
    'forbidden-seeker',
    'roleplay-trait',
    'Forbidden seeker',
    'A forbidden seeker drawn toward mysteries that wiser people leave alone.',
    'A prompt for investigation, temptation, and consequences born from curiosity.',
    'A closed door is not a warning. It is an unfinished sentence.',
    '["Follow an unanswered clue","Risk comfort for understanding"]'::jsonb,
    '["Curious","Restless","Tempted by secrets"]'::jsonb,
    '[]'::jsonb,
    '["Asks one question too many","Keeps dangerous fragments"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    20
  ),
  (
    'unproven-champion',
    'roleplay-trait',
    'Unproven champion',
    'An unproven champion determined to earn a place no one can question.',
    'A prompt for ambition, insecurity, rivalry, and meaningful recognition.',
    'Every success is evidence that you deserve the place you have fought to reach.',
    '["Volunteer for the hard task","Turn doubt into visible effort"]'::jsonb,
    '["Ambitious","Prepared","Sensitive to doubt"]'::jsonb,
    '[]'::jsonb,
    '["Hides uncertainty behind preparation","Remembers every slight"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    30
  ),
  (
    'bright-hearted-wanderer',
    'roleplay-trait',
    'Bright-hearted wanderer',
    'A bright-hearted wanderer who keeps the group moving when courage runs thin.',
    'A prompt for humour, morale, hidden sadness, and emotional leadership.',
    'Hope is not denial. It is something you practise until others can carry it too.',
    '["Break tension with warmth","Help the group recover after a setback"]'::jsonb,
    '["Warm","Resilient","Emotionally perceptive"]'::jsonb,
    '[]'::jsonb,
    '["Names camp meals","Deflects concern with a story"]'::jsonb,
    '[]'::jsonb,
    false,
    'dnd-companion-mvp',
    '2026-06-mvp',
    40
  )
on conflict (slug) do update
set
  category = excluded.category,
  name = excluded.name,
  summary = excluded.summary,
  gameplay = excluded.gameplay,
  flavour = excluded.flavour,
  actions = excluded.actions,
  traits = excluded.traits,
  proficiencies = excluded.proficiencies,
  quirks = excluded.quirks,
  ability_summaries = excluded.ability_summaries,
  magic_capable = excluded.magic_capable,
  source = excluded.source,
  source_version = excluded.source_version,
  display_order = excluded.display_order,
  updated_at = now();
